CREATE SCHEMA "DailySpells"
    AUTHORIZATION postgres;


CREATE TABLE "DailySpells"."Races"
(
    "Name" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT "Races_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE "DailySpells"."Races"
    OWNER to postgres;

CREATE TABLE "DailySpells"."Classes"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ClassName" character varying(256) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Classes_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE "DailySpells"."Classes"
    OWNER to postgres;


CREATE TABLE "DailySpells"."Character"
(
    "Name" character varying(128) COLLATE pg_catalog."default" NOT NULL,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "raceId" integer NOT NULL,
    CONSTRAINT "Character_pkey" PRIMARY KEY (id),
    CONSTRAINT "PK_Character_Race" FOREIGN KEY ("raceId")
        REFERENCES "DailySpells"."Races" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE "DailySpells"."Character"
    OWNER to postgres;


CREATE TABLE "DailySpells"."CharacterClass"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "characterId" integer NOT NULL,
    "classId" integer,
    level integer,
    CONSTRAINT "CharacterClass_pkey" PRIMARY KEY (id),
    CONSTRAINT "FK_CharacterClass_Character" FOREIGN KEY ("characterId")
        REFERENCES "DailySpells"."Character" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "PK_CharacterClass_Classes" FOREIGN KEY ("classId")
        REFERENCES "DailySpells"."Classes" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE "DailySpells"."CharacterClass"
    OWNER to postgres;


CREATE TABLE "DailySpells"."CharacterStats"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "characterId" integer NOT NULL,
    str integer NOT NULL,
    dex integer NOT NULL,
    con integer NOT NULL,
    "int" integer NOT NULL,
    wis integer NOT NULL,
    cha integer NOT NULL,
    CONSTRAINT "CharacterStats_pkey" PRIMARY KEY (id),
    CONSTRAINT "FK_CharacterStats_Character" FOREIGN KEY ("characterId")
        REFERENCES "DailySpells"."Character" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE "DailySpells"."CharacterStats"
    OWNER to postgres;




	

	
	
CREATE INDEX "fki_PK_Race"
ON "DailySpells"."Character" USING btree
("raceId" ASC NULLS LAST)
TABLESPACE pg_default;

	
	
CREATE INDEX "fki_PK_CharacterClass_Classes"
    ON "DailySpells"."CharacterClass" USING btree
    ("classId" ASC NULLS LAST)
    TABLESPACE pg_default;
	
	CREATE INDEX "fki_FK_CharacterStats_Character"
    ON "DailySpells"."CharacterStats" USING btree
    ("characterId" ASC NULLS LAST)
    TABLESPACE pg_default;

